### ISSUE TITLE
Question about hosting

### ISSUE THREAD

**Issue by Ricardo1980** [mongodb-developer/realm-binary-tree-docc#1]
Hello,

I see you are hosting the documentation in netlify.
Is it possible to use GitHub pages and just upload it to a github repo? Seems easier to maintain.

I see in apple documentation something about apache rules, so not sure if that is possible.

Thanks a lot.

**Comment by dfreniche** [comment]
Hi!

That's exactly the main problem: you need two rewrite rules as the web app that generates DocC needs these two rules. I'll revisit this for a future post on this and see what can be done (if any)

Thanks for the feedback. Will close this one. Ping me here or have a look at our Blog to watch out for that hosting post when it's done: https://www.mongodb.com/developer/learn/?content=articles#main 

Thanks!

**Comment by dfreniche** [comment]
@Ricardo1980 Post published!

https://www.mongodb.com/developer/how-to/build-host-docc-documentation-using-github-actions-netlify/
